/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.sql.Connection;
import javax.swing.JOptionPane;
import Controlador.Conexion;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author felip
 */
public class IniciarSesion extends javax.swing.JFrame {

    public PreparedStatement ps;
    public ResultSet rs;
    MenuPrincipal menu;
    MenuPrincipal1 menu2;
    VentanaRecuperar RC =new VentanaRecuperar();
   String rfc="";
   String rfc2="";
   String empleado;

    public IniciarSesion() {
        initComponents();
        this.setResizable(false);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        centro = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cUsuario = new javax.swing.JTextField();
        bIniciar = new javax.swing.JButton();
        cContrasena = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        RecupContra = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        principal.setBackground(new java.awt.Color(51, 51, 51));
        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 120)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("OnooF");
        principal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 290, 90));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        principal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 20, 80, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/torre-de-pc (1).png"))); // NOI18N
        principal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 80, 100));

        getContentPane().add(principal, java.awt.BorderLayout.PAGE_START);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Todos los derechos reservados 2023");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, java.awt.BorderLayout.PAGE_END);

        centro.setBackground(new java.awt.Color(255, 255, 255));
        centro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel7.setText("Iniciar sesión ");

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 29)); // NOI18N
        jLabel8.setText("Nombre usuario: ");

        cUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 102)));
        cUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUsuarioActionPerformed(evt);
            }
        });
        cUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cUsuarioKeyTyped(evt);
            }
        });

        bIniciar.setBackground(new java.awt.Color(0, 0, 0));
        bIniciar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bIniciar.setForeground(new java.awt.Color(255, 255, 255));
        bIniciar.setText("Iniciar sesión ");
        bIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIniciarActionPerformed(evt);
            }
        });

        cContrasena.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cContrasena.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51)));
        cContrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cContrasenaKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 29)); // NOI18N
        jLabel9.setText("Contraseña: ");

        RecupContra.setBackground(new java.awt.Color(0, 0, 0));
        RecupContra.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        RecupContra.setForeground(new java.awt.Color(255, 255, 255));
        RecupContra.setText("Recuperar contraseña");
        RecupContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecupContraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(bIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(168, 168, 168))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(RecupContra, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(58, 58, 58)
                    .addComponent(jLabel9)
                    .addContainerGap(360, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addGap(41, 41, 41)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(cUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(cContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RecupContra)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(264, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addGap(192, 192, 192)))
        );

        centro.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 580, 500));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/re (1).jpg"))); // NOI18N
        centro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 700));

        getContentPane().add(centro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cUsuarioActionPerformed

    private void bIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIniciarActionPerformed
        menu = new MenuPrincipal();
        menu2 = new MenuPrincipal1();
        Connection conexion = null;
        String usuario;
        String contrasena;
        String rol;

        try
        {
            conexion = Conexion.getConexion();
            ps = conexion.prepareStatement("select *from usuario where cusuario=?");
            ps.setString(1, cUsuario.getText());
            rs = ps.executeQuery();

            if (rs.next())
            {
                usuario = rs.getString("cusuario");
                contrasena = rs.getString("contrasena");
                rol = rs.getString("tipo_usuario");
                rfc = rs.getString("RFCUsuario");
                rfc2 = rfc;
                if ((usuario.equals(cUsuario.getText()) && contrasena.equals(cContrasena.getText())) && (rol.equals("Administrador")))
                {
                    JOptionPane entrar= new JOptionPane();
                    entrar.setLocation(500, 250);
                    entrar.showMessageDialog(null, "Bienvenido Administrador");
                    this.setVisible(false);
                    menu.setVisible(true);
                } else if ((usuario.equals(cUsuario.getText()) && contrasena.equals(cContrasena.getText()) && (rol.equals("Empleado"))))
                {
                    JOptionPane.showMessageDialog(null, "Bienvenido Empleado");
                    this.setVisible(false);
                    menu2.setVisible(true);
                } else
                {
                    JOptionPane.showMessageDialog(null, "Error al iniciar sesion,Usuario incorrecto o contraseña");
                    limpiarCajasLogin();
                }
            } else
            {
                JOptionPane ventanaNoRegistrado = new JOptionPane();
                ventanaNoRegistrado.showMessageDialog(null, "Usuario no registrado");
                limpiarCajasLogin();
            }
            rs.close();
            ps.close();
            //conexion.close();
        } catch (Exception ex)
        {
            //JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_bIniciarActionPerformed

    private void RecupContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecupContraActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        RC.setVisible(true);
    }//GEN-LAST:event_RecupContraActionPerformed

    private void cUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cUsuarioKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            bIniciar.doClick();
        }
    }//GEN-LAST:event_cUsuarioKeyTyped

    private void cContrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cContrasenaKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            bIniciar.doClick();}
        
    }//GEN-LAST:event_cContrasenaKeyTyped
    private void limpiarCajasLogin() {
        cUsuario.setText("");
        cContrasena.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    public String getRfc(){
        return rfc2;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RecupContra;
    private javax.swing.JButton bIniciar;
    private javax.swing.JPasswordField cContrasena;
    private javax.swing.JTextField cUsuario;
    private javax.swing.JPanel centro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel principal;
    // End of variables declaration//GEN-END:variables
}
