/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


/**
 *
 * @author felip
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    IniciarSesion inicio = new IniciarSesion();
    VentanaVenta venVenta = new VentanaVenta();
    VentanaInventario venInventario = new VentanaInventario();
    VentanaPuntoVenta venPuntoVenta = new VentanaPuntoVenta();
    VentanaEmpleado venUsuario = new VentanaEmpleado();
    CarritoVenta carrito;
    VentanaProveedor provedor = new VentanaProveedor();
    VentanaCliente venReparaciones = new VentanaCliente();

    public MenuPrincipal() {
        initComponents();
        this.setResizable(false);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        centro = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        principal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        salirMenuP = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        mostrarCarrito = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        botonUsuario = new javax.swing.JButton();
        botonProveedores = new javax.swing.JButton();
        botonInventario = new javax.swing.JButton();
        botonPuntoVenta = new javax.swing.JButton();
        botonVenta = new javax.swing.JButton();
        reparar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Todos los derechos reservados 2023");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, java.awt.BorderLayout.PAGE_END);

        centro.setBackground(new java.awt.Color(255, 255, 255));
        centro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/re (1).jpg"))); // NOI18N
        centro.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, 700));

        getContentPane().add(centro, java.awt.BorderLayout.CENTER);

        principal.setBackground(new java.awt.Color(51, 51, 51));
        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 120)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("OnooF");
        principal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 290, 100));

        salirMenuP.setBackground(new java.awt.Color(204, 204, 204));
        salirMenuP.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        salirMenuP.setText("Salir");
        salirMenuP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMenuPActionPerformed(evt);
            }
        });
        principal.add(salirMenuP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 80, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/torre-de-pc (1).png"))); // NOI18N
        principal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 80, 100));

        mostrarCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrito-de-compras (3).png"))); // NOI18N
        mostrarCarrito.setContentAreaFilled(false);
        mostrarCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarCarritoActionPerformed(evt);
            }
        });
        principal.add(mostrarCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, -1, -1));

        getContentPane().add(principal, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 102, 0));
        jPanel2.setLayout(new java.awt.GridLayout(6, 1));

        botonUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonUsuario.setForeground(new java.awt.Color(255, 255, 255));
        botonUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados.png"))); // NOI18N
        botonUsuario.setText("Empleados");
        botonUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonUsuario.setContentAreaFilled(false);
        botonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(botonUsuario);

        botonProveedores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonProveedores.setForeground(new java.awt.Color(255, 255, 255));
        botonProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cartero.png"))); // NOI18N
        botonProveedores.setText("Proveedores");
        botonProveedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonProveedores.setContentAreaFilled(false);
        botonProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProveedoresActionPerformed(evt);
            }
        });
        jPanel2.add(botonProveedores);

        botonInventario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonInventario.setForeground(new java.awt.Color(255, 255, 255));
        botonInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventario (1).png"))); // NOI18N
        botonInventario.setText("Catálogo de productos");
        botonInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonInventario.setContentAreaFilled(false);
        botonInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInventarioActionPerformed(evt);
            }
        });
        jPanel2.add(botonInventario);

        botonPuntoVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonPuntoVenta.setForeground(new java.awt.Color(255, 255, 255));
        botonPuntoVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/vendedor.png"))); // NOI18N
        botonPuntoVenta.setText("Punto de venta");
        botonPuntoVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonPuntoVenta.setContentAreaFilled(false);
        botonPuntoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoVentaActionPerformed(evt);
            }
        });
        jPanel2.add(botonPuntoVenta);

        botonVenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonVenta.setForeground(new java.awt.Color(255, 255, 255));
        botonVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bienes.png"))); // NOI18N
        botonVenta.setText("Ventas");
        botonVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botonVenta.setContentAreaFilled(false);
        botonVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentaActionPerformed(evt);
            }
        });
        jPanel2.add(botonVenta);

        reparar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reparar.setForeground(new java.awt.Color(255, 255, 255));
        reparar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inventario (3).png"))); // NOI18N
        reparar.setText("Reparaciones");
        reparar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reparar.setContentAreaFilled(false);
        reparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repararActionPerformed(evt);
            }
        });
        jPanel2.add(reparar);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMenuPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMenuPActionPerformed
        this.setVisible(false);
        venVenta.setVisible(false);
        venInventario.setVisible(false);
        venPuntoVenta.setVisible(false);
        venUsuario.setVisible(false);
        venReparaciones.setVisible(false);
        inicio.setVisible(true);
    }//GEN-LAST:event_salirMenuPActionPerformed

    private void botonPuntoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoVentaActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        venPuntoVenta.setVisible(false);
        venUsuario.setVisible(false);
        venInventario.setVisible(false);
        venReparaciones.setVisible(false);
        venPuntoVenta.mostrarTabla();
        venPuntoVenta.setVisible(true);
    }//GEN-LAST:event_botonPuntoVentaActionPerformed

    private void botonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuarioActionPerformed
        venVenta.setVisible(false);
        venInventario.setVisible(false);
        venPuntoVenta.setVisible(false);
        venReparaciones.setVisible(false);
        venUsuario.setVisible(true);
    }//GEN-LAST:event_botonUsuarioActionPerformed

    private void botonVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentaActionPerformed
        // TODO add your handling code here:
        venInventario.setVisible(false);
        venPuntoVenta.setVisible(false);
        venUsuario.setVisible(false);
        venReparaciones.setVisible(false);
        venVenta.setVisible(true);
        venVenta.mostrarTabla();
    }//GEN-LAST:event_botonVentaActionPerformed

    private void botonInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInventarioActionPerformed
        // TODO add your handling code here:
        venPuntoVenta.setVisible(false);
        venUsuario.setVisible(false);
        venVenta.setVisible(false);
        venInventario.mostrarTabla();
        venReparaciones.setVisible(false);
        venInventario.setVisible(true);
    }//GEN-LAST:event_botonInventarioActionPerformed

    private void mostrarCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarCarritoActionPerformed
        // TODO add your handling code here:
        carrito = new CarritoVenta(null, true);
        carrito.setLocation(1000, 50);
        carrito.setVisible(true);
    }//GEN-LAST:event_mostrarCarritoActionPerformed

    private void botonProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProveedoresActionPerformed
        // TODO add your handling code here:
        venVenta.setVisible(false);
        venInventario.setVisible(false);
        venPuntoVenta.setVisible(false);
        venUsuario.setVisible(false);
        venReparaciones.setVisible(false);
        provedor.setVisible(true);
    }//GEN-LAST:event_botonProveedoresActionPerformed

    private void repararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repararActionPerformed
        // TODO add your handling code here:
        venVenta.setVisible(false);
        venInventario.setVisible(false);
        venPuntoVenta.setVisible(false);
        venUsuario.setVisible(false);
        venReparaciones.setVisible(true);
        provedor.setVisible(false);
        venReparaciones.mostrarTabla();
        
    }//GEN-LAST:event_repararActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInventario;
    private javax.swing.JButton botonProveedores;
    private javax.swing.JButton botonPuntoVenta;
    private javax.swing.JButton botonUsuario;
    private javax.swing.JButton botonVenta;
    private javax.swing.JPanel centro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton mostrarCarrito;
    private javax.swing.JPanel principal;
    private javax.swing.JButton reparar;
    private javax.swing.JButton salirMenuP;
    // End of variables declaration//GEN-END:variables
}
