/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controlador.Conexion;

/**
 *
 * @author nfswo
 */
public class VentanaReparaciones extends javax.swing.JFrame {

    public PreparedStatement ps, ps1;
    public ResultSet rs;
    public DefaultTableModel dft;
    int resultado;
    VentanaEntregaProducto vpro = new VentanaEntregaProducto();

    public VentanaReparaciones() {
        initComponents();
        this.setLocation(270, 165);
        //this.setAlwaysOnTop(true);
        mostrarTabla();
        mostrarTablaP();
        seleccionarTabla();

    }

    public void mostrarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        rs = Conexion.getTabla("select *from reparacion");
        //se asignan los nombre de la columna
        modelo.setColumnIdentifiers(new Object[]{
            "ID_Reparacion", "ID_Producto", "ID_Cliente", "Descripción", "Fecha", "Total", "Entrega Lista"});

        try {
            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString("id_Reparacion"),
                    rs.getString("id_producto"),
                    rs.getString("id_cliente"),
                    rs.getString("descripcion"),
                    rs.getString("fecha"),
                    rs.getString("total"),
                    rs.getString("entrega_lista")
                });

            }
            tablaInsumos.setModel(modelo);
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(null, e);
        }
        //seleccionarTabla();
    }

    public void mostrarTablaP() {
        DefaultTableModel modelo = new DefaultTableModel();
        rs = Conexion.getTabla("select *from inventario");
        //se asignan los nombre de la columna
        modelo.setColumnIdentifiers(new Object[]{
            "ID Producto", "Nombre del producto", "Descripción", "Cantidad de existencia", "Precio unidad"});

        try {
            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString("id_producto"),
                    rs.getString("nombre_producto"),
                    rs.getString("descripcion"),
                    rs.getString("cantidad_existencia"),
                    rs.getString("precio_unidad")
                });

            }
            tProductos.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        //seleccionarTabla();
    }

    public void limpiar() {
        cId.setText("");
        cProducto.setText("");
        buscador.setSelectedItem(null);
        cBuscar.setText("");
        cCliente.setText("");
        cDescripcion.setText("");
        cFecha.setText("");
        cPrecio.setText("");
        tProductos.setRowSelectionAllowed(false);
        botonRegistrar.setEnabled(true);
        mostrarTabla();
        mostrarTablaP();

    }

    private void seleccionarTabla() {
        tablaInsumos.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                limpiar();
                int row = tablaInsumos.rowAtPoint(e.getPoint());
                cId.setText(tablaInsumos.getValueAt(row, 0).toString());
                cProducto.setText(tablaInsumos.getValueAt(row, 1).toString());
                cCliente.setText(tablaInsumos.getValueAt(row, 2).toString());
                cDescripcion.setText(tablaInsumos.getValueAt(row, 3).toString());
                cFecha.setText(tablaInsumos.getValueAt(row, 4).toString());
                cPrecio.setText(tablaInsumos.getValueAt(row, 5).toString());
                botonRegistrar.setEnabled(false);

            }
        });

    }

    /*public void mostrarComboProv() {
        try
        {
            rs = Conexion.getTabla("select *from proveedor");
            while (rs.next())
            {
                comboBuscar.addItem(rs.getString("nombre"));
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(VentanaInsumos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tProductos = new javax.swing.JTable();
        bEliminar = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        bActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cCliente = new javax.swing.JTextField();
        cFecha = new javax.swing.JTextField();
        cDescripcion = new javax.swing.JTextField();
        cPrecio = new javax.swing.JTextField();
        bLimpiar = new javax.swing.JButton();
        cId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        buscador = new javax.swing.JComboBox<>();
        cBuscar = new javax.swing.JTextField();
        cProducto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaInsumos = new javax.swing.JTable();
        bEntregaPro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        botonSalir.setBackground(new java.awt.Color(51, 51, 51));
        botonSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setToolTipText("");

        tProductos.setBackground(new java.awt.Color(153, 153, 153));
        tProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tProductos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tProductos.setAutoscrolls(false);
        tProductos.setEnabled(false);
        tProductos.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(tProductos);

        bEliminar.setBackground(new java.awt.Color(51, 51, 51));
        bEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bEliminar.setForeground(new java.awt.Color(255, 255, 255));
        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        botonRegistrar.setBackground(new java.awt.Color(51, 51, 51));
        botonRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        bActualizar.setBackground(new java.awt.Color(51, 51, 51));
        bActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bActualizar.setForeground(new java.awt.Color(255, 255, 255));
        bActualizar.setText("Actualizar");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cajero.png"))); // NOI18N
        jLabel1.setText("Registro de Reparaciones");

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel2.setText("ID_Producto:");

        jLabel3.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel3.setText("Id:");

        jLabel5.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel5.setText("ID_Cliente:");

        cCliente.setEditable(true);
        cCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cClienteActionPerformed(evt);
            }
        });
        cCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cClienteKeyTyped(evt);
            }
        });

        cFecha.setEditable(true);
        cFecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cFecha.setToolTipText("");
        cFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDescripcionActionPerformed(evt);
            }
        });

        cPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cPrecio.setToolTipText("");
        cPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cPrecioActionPerformed(evt);
            }
        });
        cPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cPrecioKeyTyped(evt);
            }
        });

        bLimpiar.setBackground(new java.awt.Color(51, 51, 51));
        bLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        cId.setEditable(true);
        cId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cIdActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel7.setText("Fecha:");

        jLabel8.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel8.setText("Descripcion:");

        jLabel9.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel9.setText("Precio total:");

        botonBuscar.setBackground(new java.awt.Color(51, 51, 51));
        botonBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        buscador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buscador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "id", "ID_Cliente", "Precio", "Entrega lista" }));
        buscador.setSelectedItem(null);
        buscador.setBorder(null);
        buscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscadorActionPerformed(evt);
            }
        });

        cBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBuscarActionPerformed(evt);
            }
        });

        cProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cProductoKeyTyped(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setToolTipText("");

        tablaInsumos.setBackground(new java.awt.Color(153, 153, 153));
        tablaInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaInsumos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaInsumos.setAutoscrolls(false);
        tablaInsumos.setEnabled(false);
        tablaInsumos.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setViewportView(tablaInsumos);

        bEntregaPro.setBackground(new java.awt.Color(51, 51, 51));
        bEntregaPro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bEntregaPro.setForeground(new java.awt.Color(255, 255, 255));
        bEntregaPro.setText("Entrega Producto");
        bEntregaPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntregaProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(293, 293, 293)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cId, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(174, 174, 174)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cProducto, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cDescripcion)
                                            .addComponent(cFecha)
                                            .addComponent(cCliente)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(cPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(42, 42, 42))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(bActualizar)
                                .addGap(70, 70, 70)
                                .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(bLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(cBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bEntregaPro))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSalir)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cProducto))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(cPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bEntregaPro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))))
        );

        cId.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1068, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:

        int option = JOptionPane.showConfirmDialog(null, "¿Deseas continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            try {
                Connection conexion = Conexion.getConexion();
                ps = conexion.prepareStatement("delete from reparacion where id_Reparacion=?");
                ps.setString(1, cId.getText());
                int resultado = ps.executeUpdate();
                if (resultado > 0) {
                    JOptionPane.showMessageDialog(null, "Eliminacion correcta");
                    mostrarTabla();
                } else {
                    JOptionPane.showMessageDialog(null, "No se realizo la eliminación de los datos");
                }
                conexion.close();
            } catch (Exception e) {
                System.err.println(e);
            }
            limpiar();
            tProductos.setRowSelectionAllowed(false);
            botonRegistrar.setEnabled(true);
        } else {
            System.out.println("El usuario seleccionó 'No'.");
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO add your handling code here:

        int option = JOptionPane.showConfirmDialog(null, "¿Deseas continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            Connection conexion = null;
            int resultado = 0;
            boolean yaRegistrado;
            try {
                conexion = Conexion.getConexion();
                ps = conexion.prepareStatement("insert into reparacion (id_producto,id_cliente,descripcion,fecha,total)values(?,?,?,?,?)");
                ps.setString(1, cProducto.getText());
                ps.setString(2, cCliente.getText());
                ps.setString(3, cDescripcion.getText());
                ps.setString(4, cFecha.getText());
                ps.setString(5, cPrecio.getText());

                ps1 = conexion.prepareStatement("UPDATE inventario\n"
                        + "SET cantidad_existencia= cantidad_existencia-1\n"
                        + "WHERE id_producto=?");
                ps1.setString(1, cProducto.getText());

                if (!"".equals(cCliente.getText())
                        && !"".equals(cPrecio.getText())) {

                    resultado = ps.executeUpdate(); //ejecutamos la inserccion
                    ps1.executeUpdate();

                }
                if ((resultado > 0)) {
                    JOptionPane.showMessageDialog(null, "Datos ingresados correctamente");
                    limpiar();
                    mostrarTabla();
                    mostrarTablaP();
                } else {
                    JOptionPane.showMessageDialog(null, "Verifique que los datos sean correctos");

                }
                conexion.close();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Verifique los datos");
                System.out.println(ex);
            }
            tProductos.setRowSelectionAllowed(false);
            botonRegistrar.setEnabled(true);
        } else {

        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        // TODO add your handling code here:

        int option = JOptionPane.showConfirmDialog(null, "¿Deseas continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            resultado = 0;
            try {
                Connection conexion = Conexion.getConexion();
                ps = conexion.prepareStatement("update reparacion set id_producto=?,id_cliente=?,descripcion=?,fecha=?,total=? where id_Reparacion=?");

                ps.setString(1, cProducto.getText());
                ps.setString(2, cCliente.getText());
                ps.setString(3, cDescripcion.getText());
                ps.setString(4, cFecha.getText());
                ps.setString(5, cPrecio.getText());
                ps.setString(6, cId.getText());
                resultado = ps.executeUpdate();

                if ((resultado > 0)) {
                    JOptionPane.showMessageDialog(null, "Datos actualizados correctamente");
                    limpiar();
                } else {
                    JOptionPane.showMessageDialog(null, "No fue posible actualizar los datos");
                }
                conexion.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Verifique los datos");
            }
            mostrarTabla();
            limpiar();
            tProductos.setRowSelectionAllowed(false);
            botonRegistrar.setEnabled(true);
        } else {

        }
    }//GEN-LAST:event_bActualizarActionPerformed

    private void cClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cClienteActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void cIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cIdActionPerformed

    private void cPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cPrecioActionPerformed

    private void cDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cDescripcionActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // TODO add your handling code here:
        //aca buscar

        DefaultTableModel modelo1 = new DefaultTableModel();
        Connection conexion = null;
        modelo1.setColumnIdentifiers(new Object[]{
            "Id", "ID_Producto", "ID_Cliente", "Descripcion", "Fecha", "Total","Entrega lista"});
        String donde = buscador.getSelectedItem().toString();
        switch (donde) {
            case "id":
        try {
                conexion = Conexion.getConexion();
                ps = conexion.prepareStatement("select *from reparacion where id_Reparacion=?");
                ps.setString(1, cBuscar.getText());
                rs = ps.executeQuery();
                while (rs.next()) {
                    modelo1.addRow(new Object[]{
                        rs.getString("id_Reparacion"),
                        rs.getString("id_producto"),
                        rs.getString("id_cliente"),
                        rs.getString("descripcion"),
                        rs.getString("fecha"),
                        rs.getString("total")
                    });

                }
                tProductos.setModel(modelo1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            break;

            case "Producto":
//                
            try {
                JOptionPane.showMessageDialog(rootPane, "Entre a producto");
                conexion =Conexion.getConexion();
                ps = conexion.prepareStatement("select *from reparacion where id_producto=?");
                ps.setString(1, cBuscar.getText());
                rs = ps.executeQuery();
                while (rs.next()) {
                    modelo1.addRow(new Object[]{
                        rs.getString("id_Reparacion"),
                        rs.getString("id_producto"),
                        rs.getString("id_cliente"),
                        rs.getString("descripcion"),
                        rs.getString("fecha"),
                        rs.getString("total")
                    });

                }
                tProductos.setModel(modelo1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            break;

            case "Cliente":
try {
                JOptionPane.showMessageDialog(rootPane, "Entre a clientes");
                conexion = Conexion.getConexion();
                ps = conexion.prepareStatement("select *from reparacion where id_cliente=?");
                ps.setString(1, cBuscar.getText());
                rs = ps.executeQuery();
                while (rs.next()) {
                    modelo1.addRow(new Object[]{
                        rs.getString("id_Reparacion"),
                        rs.getString("id_producto"),
                        rs.getString("id_cliente"),
                        rs.getString("descripcion"),
                        rs.getString("fecha"),
                        rs.getString("total")
                    });

                }
                tProductos.setModel(modelo1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            break;

            case "Descripción":
try {
                conexion = Conexion.getConexion();
                ps = conexion.prepareStatement("select *from reparacion where descripcion=?");
                ps.setString(1, cBuscar.getText());
                rs = ps.executeQuery();
                while (rs.next()) {
                    modelo1.addRow(new Object[]{
                        rs.getString("id_Reparacion"),
                        rs.getString("id_producto"),
                        rs.getString("id_cliente"),
                        rs.getString("descripcion"),
                        rs.getString("fecha"),
                        rs.getString("total")
                    });

                }
                tProductos.setModel(modelo1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            break;

            case "Fecha":
try {
                conexion = Conexion.getConexion();
                ps = conexion.prepareStatement("select *from reparacion where fecha=?");
                ps.setString(1, cBuscar.getText());
                rs = ps.executeQuery();
                while (rs.next()) {
                    modelo1.addRow(new Object[]{
                        rs.getString("id_Reparacion"),
                        rs.getString("id_producto"),
                        rs.getString("id_cliente"),
                        rs.getString("descripcion"),
                        rs.getString("fecha"),
                        rs.getString("total")
                    });

                }
                tProductos.setModel(modelo1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            break;

            case "Entrega lista":
try {
                conexion = Conexion.getConexion();
                ps = conexion.prepareStatement("select *from reparacion where entrega_lista=?");
                ps.setString(1, cBuscar.getText());
                rs = ps.executeQuery();
                while (rs.next()) {
                    modelo1.addRow(new Object[]{
                        rs.getString("id_Reparacion"),
                        rs.getString("id_producto"),
                        rs.getString("id_cliente"),
                        rs.getString("descripcion"),
                        rs.getString("fecha"),
                        rs.getString("total"),
                        rs.getString("entrega_lista")
                    });

                }
                tablaInsumos.setModel(modelo1);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            break;

        }


    }//GEN-LAST:event_botonBuscarActionPerformed

    private void cBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cBuscarActionPerformed

    private void buscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscadorActionPerformed

    private void cPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cPrecioKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (!Character.isDigit(key) && key != '.') {
            evt.consume();
        }
    }//GEN-LAST:event_cPrecioKeyTyped

    private void cProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cProductoKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (!Character.isDigit(key)) {
            evt.consume();
        }
    }//GEN-LAST:event_cProductoKeyTyped

    private void cClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cClienteKeyTyped
        // TODO add your handling code here:
        char key = evt.getKeyChar();
        if (!Character.isDigit(key)) {
            evt.consume();
        }
    }//GEN-LAST:event_cClienteKeyTyped

    private void bEntregaProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntregaProActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        vpro.setVisible(true);
    }//GEN-LAST:event_bEntregaProActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bEntregaPro;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JButton botonSalir;
    public javax.swing.JComboBox<String> buscador;
    private javax.swing.JTextField cBuscar;
    private javax.swing.JTextField cCliente;
    private javax.swing.JTextField cDescripcion;
    private javax.swing.JTextField cFecha;
    private javax.swing.JTextField cId;
    private javax.swing.JTextField cPrecio;
    private javax.swing.JTextField cProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tProductos;
    private javax.swing.JTable tablaInsumos;
    // End of variables declaration//GEN-END:variables

}
