package Vista;

import ControlEmpleados.Empleado;
import ControlEmpleados.EmpleadoDAOProxy;
import ControlEmpleados.IEmpleadoDAO;
import ControlProveedores.IProveedoresDAO;
import ControlProveedores.Proveedor;
import ControlProveedores.ProveedorDAOProxy;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controlador.Conexion;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author felip
 */
public class VentanaEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form ventana1
     */
    
    VentanaUsuario venUsuario1 = new VentanaUsuario();
    private Empleado empleadoSeleccionado;
    Empleado prov = new Empleado();
    private ArrayList<Empleado> listap = new ArrayList();
DefaultTableModel pmodelo = new DefaultTableModel();
private IEmpleadoDAO proxy;
    private ArrayList<String> empleadosElimados = new ArrayList<>();
    
    DefaultTableModel modelo;

    public VentanaEmpleado() {
        initComponents();
        this.setLocation(270, 165);
        proxy = new EmpleadoDAOProxy();
        
        modelo=(DefaultTableModel) tablaUsuarios.getModel();
        modelo.setColumnIdentifiers(new Object[]
        {
            "RFC", "Nombre", "A. paternos", "A. maternos", "direccio", "correo"
        });
        listaEmpleados();
    }

     public void listaEmpleados() {
        listap = new ArrayList<Empleado>();
        listap = (ArrayList) proxy.listaEmpleados();
        pmodelo = (DefaultTableModel) tablaUsuarios.getModel();
        pmodelo.setRowCount(0);
        Object[] ob = new Object[6];
        for (int i = 0; i < listap.size(); i++) {
            ob[0] = listap.get(i).getRFC();
            ob[1] = listap.get(i).getNombre();
            ob[2] = listap.get(i).getApaterno();
            ob[3] = listap.get(i).getAmaterno();
            ob[4] = listap.get(i).getDireccion();
            ob[5] = listap.get(i).getCorreo();
            pmodelo.addRow(ob);
        }
        tablaUsuarios.setModel(pmodelo);
    }

    public void modificar() {
        int fila = tablaUsuarios.getSelectedRow();

        if (fila >= 0) {
            cRFC.setText(tablaUsuarios.getValueAt(fila, 0).toString());
            cNombre.setText(tablaUsuarios.getValueAt(fila, 1).toString());
            cPaterno.setText(tablaUsuarios.getValueAt(fila, 2).toString());
            cMaterno.setText(tablaUsuarios.getValueAt(fila, 3).toString());
            cDireccion.setText(tablaUsuarios.getValueAt(fila, 4).toString());
            cCorreo.setText(tablaUsuarios.getValueAt(fila, 5).toString());
        } else {
            JOptionPane.showMessageDialog(null, "Fila no seleccionada");

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        bEliminar = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        bActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cNombre = new javax.swing.JTextField();
        cPaterno = new javax.swing.JTextField();
        cMaterno = new javax.swing.JTextField();
        cCorreo = new javax.swing.JTextField();
        bLimpiar = new javax.swing.JButton();
        cDireccion = new javax.swing.JTextField();
        cRFC = new javax.swing.JTextField();
        rUsuario = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        botonSalir.setBackground(new java.awt.Color(51, 51, 51));
        botonSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setToolTipText("");

        tablaUsuarios.setBackground(new java.awt.Color(153, 153, 153));
        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tablaUsuarios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaUsuarios.setAutoscrolls(false);
        tablaUsuarios.setSelectionBackground(new java.awt.Color(102, 102, 102));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        bEliminar.setBackground(new java.awt.Color(51, 51, 51));
        bEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bEliminar.setForeground(new java.awt.Color(255, 255, 255));
        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        botonRegistrar.setBackground(new java.awt.Color(51, 51, 51));
        botonRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        bActualizar.setBackground(new java.awt.Color(51, 51, 51));
        bActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bActualizar.setForeground(new java.awt.Color(255, 255, 255));
        bActualizar.setText("Actualizar");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/empleados.png"))); // NOI18N
        jLabel1.setText("Empleados");

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel2.setText("Apellido paterno: ");

        jLabel3.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel4.setText("Apellido materno: ");

        jLabel5.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel5.setText("RFC:");

        jLabel6.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel6.setText("Dirección:");

        jLabel8.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel8.setText("Correo:");

        cNombre.setEditable(true);
        cNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNombreActionPerformed(evt);
            }
        });
        cNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cNombreKeyTyped(evt);
            }
        });

        cPaterno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cPaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cPaternoKeyTyped(evt);
            }
        });

        cMaterno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cMaterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cMaternoActionPerformed(evt);
            }
        });
        cMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cMaternoKeyTyped(evt);
            }
        });

        cCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cCorreoFocusLost(evt);
            }
        });
        cCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCorreoActionPerformed(evt);
            }
        });
        cCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cCorreoKeyTyped(evt);
            }
        });

        bLimpiar.setBackground(new java.awt.Color(51, 51, 51));
        bLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        cDireccion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cRFC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cRFC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cRFC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cRFCActionPerformed(evt);
            }
        });
        cRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cRFCKeyTyped(evt);
            }
        });

        rUsuario.setBackground(new java.awt.Color(51, 51, 51));
        rUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rUsuario.setForeground(new java.awt.Color(255, 255, 255));
        rUsuario.setText("Registrar usuario");
        rUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rUsuarioActionPerformed(evt);
            }
        });

        jButton1.setText("Refrescar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cPaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                    .addComponent(cMaterno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                    .addComponent(cCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                                    .addComponent(cRFC)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(360, 360, 360)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSalir)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cRFC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(rUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
         if(cNombre.getText().trim().isEmpty() || cRFC.getText().trim().isEmpty()
                || cDireccion.getText().trim().isEmpty() || cCorreo.getText().trim().isEmpty()|| cPaterno.getText().trim().isEmpty() ||  cMaterno.getText().trim().isEmpty() )
        {
            JOptionPane.showMessageDialog(this,"Rellene los o el campo faltante", "Error",JOptionPane.WARNING_MESSAGE);
            
        }else{ 
            //DefaultTableModel modelo = (DefaultTableModel) tablaProveedores.getModel();
        int fila = tablaUsuarios.getSelectedRow();
        try {
                empleadosElimados.add(cRFC.getText());
                proxy.eliminaEmpleado();
                modelo.removeRow(fila);
                modelo.fireTableDataChanged();
                limpiar();
            
        } catch (Exception e) {
            Logger.getLogger(VentanaProveedor.class.getName()).log(Level.SEVERE, null, e);
        }
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
      if(cNombre.getText().trim().isEmpty() || cRFC.getText().trim().isEmpty()
                || cDireccion.getText().trim().isEmpty() || cCorreo.getText().trim().isEmpty()|| cPaterno.getText().trim().isEmpty() ||  cMaterno.getText().trim().isEmpty() )
        {
            JOptionPane.showMessageDialog(this,"Rellene los o el campo faltante", "Error",JOptionPane.WARNING_MESSAGE);
            
        }else{
        if (verificamail(cCorreo.getText())) {
            prov.setRFC(cRFC.getText());
                prov.setNombre(cNombre.getText());
                prov.setApaterno(cPaterno.getText());
                prov.setAmaterno(cMaterno.getText());
                prov.setDireccion(cDireccion.getText());
                prov.setCorreo(cCorreo.getText());
                proxy.registrarEmpleado(prov);
                limpiar();
                listaEmpleados();

            

        } else {
            JOptionPane.showMessageDialog(this, "Ingresé un correo valido", "Error", JOptionPane.WARNING_MESSAGE);
        }
        tablaUsuarios.setRowSelectionAllowed(false);
        botonRegistrar.setEnabled(true);
        }

    }//GEN-LAST:event_botonRegistrarActionPerformed
   public boolean verificamail(String correo) {
        Pattern patron = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher mat = patron.matcher(correo);
        return mat.find();
    }
   
   private void limpiar() {
        cNombre.setText("");
        cPaterno.setText("");
        cMaterno.setText("");
        cRFC.setText("");
        cDireccion.setText("");
        cCorreo.setText("");
        tablaUsuarios.setRowSelectionAllowed(false);
        botonRegistrar.setEnabled(true);

    }


    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
       DefaultTableModel modelo = (DefaultTableModel) tablaUsuarios.getModel();

        int option = JOptionPane.showConfirmDialog(null, "¿Deseas continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            if (verificamail(cCorreo.getText())) {
                    prov.setRFC(cRFC.getText());
                prov.setNombre(cNombre.getText());
                prov.setApaterno(cPaterno.getText());
                prov.setAmaterno(cMaterno.getText());
                prov.setDireccion(cDireccion.getText());
                prov.setCorreo(cCorreo.getText());
                    boolean actualizacionExitosa = proxy.actualizarEmpleado(prov);

                    if (actualizacionExitosa) {
                        listaEmpleados();

                        JOptionPane.showMessageDialog(null, "Datos actualizados correctamente");
                        limpiar();
                        tablaUsuarios.setRowSelectionAllowed(false);
                        botonRegistrar.setEnabled(true);
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al actualizar en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                
            } else {
                JOptionPane.showMessageDialog(this, "Ingresé un correo valido", "Error", JOptionPane.WARNING_MESSAGE);
            }

        } else {
        }
    }//GEN-LAST:event_bActualizarActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void rUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rUsuarioActionPerformed
        this.setVisible(false);
        venUsuario1.setVisible(true);
        venUsuario1.mostrarTablaE();
    }//GEN-LAST:event_rUsuarioActionPerformed

    private void cNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNombreActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cNombreActionPerformed

    private void cMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cMaternoActionPerformed

    private void cNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_SPACE)
        {
            evt.consume();
        }
    }//GEN-LAST:event_cNombreKeyTyped

    private void cPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cPaternoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_SPACE)
        {
            evt.consume();
        }
    }//GEN-LAST:event_cPaternoKeyTyped

    private void cMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cMaternoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_SPACE)
        {
            evt.consume();
        }
    }//GEN-LAST:event_cMaternoKeyTyped

    private void cRFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cRFCKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (cRFC.getText().trim().length() == 13) {
            evt.consume();
        }
        if (!Character.isLetterOrDigit(c) && c != KeyEvent.VK_BACK_SPACE)
        {
            evt.consume();
        }
    }//GEN-LAST:event_cRFCKeyTyped

    private void cCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cCorreoKeyTyped
        // TODO add your handling code here:    
    }//GEN-LAST:event_cCorreoKeyTyped

    private void cCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCorreoActionPerformed

    private void cCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cCorreoFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cCorreoFocusLost

    private void cRFCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cRFCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cRFCActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // TODO add your handling code here:
        modificar();
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        proxy.refrescarDatos(empleadosElimados);
        listaEmpleados();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void seleccionarTabla() {
        tablaUsuarios.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                limpiar();
                int row = tablaUsuarios.rowAtPoint(e.getPoint());

                cRFC.setText(tablaUsuarios.getValueAt(row, 0).toString());
                cNombre.setText(tablaUsuarios.getValueAt(row, 1).toString());
                cPaterno.setText(tablaUsuarios.getValueAt(row, 2).toString());
                cMaterno.setText(tablaUsuarios.getValueAt(row, 3).toString());
                cDireccion.setText(tablaUsuarios.getValueAt(row, 4).toString());
                cCorreo.setText(tablaUsuarios.getValueAt(row, 5).toString());
                botonRegistrar.setEnabled(false);

                cRFC.setEditable(false);

            }
        });
        cRFC.setEditable(true);

    }

  private void validateEmail() {
        String email = cCorreo.getText().trim();

        // Patrón para validar el formato del correo electrónico
        String emailPattern = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";

        Pattern pattern = Pattern.compile(emailPattern);
        Matcher matcher = pattern.matcher(email);

        if (matcher.matches()) {
            JOptionPane.showMessageDialog(this, "Correo electrónico válido");
        } else {
            JOptionPane.showMessageDialog(this, "Correo electrónico inválido");
            cCorreo.requestFocus();
        }
    }

    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VentanaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VentanaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VentanaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VentanaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEmpleado().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField cCorreo;
    private javax.swing.JTextField cDireccion;
    private javax.swing.JTextField cMaterno;
    private javax.swing.JTextField cNombre;
    private javax.swing.JTextField cPaterno;
    private javax.swing.JTextField cRFC;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rUsuario;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
