/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controlador.Conexion;

/**
 *
 * @author nfswo
 */
public class VentanaCliente extends javax.swing.JFrame {

    public PreparedStatement ps, ps1;
    public ResultSet rs;
    public DefaultTableModel dft;
    int resultado;
    VentanaReparaciones vr =new VentanaReparaciones();

    /**
     * Creates new form VentanaInsumos
     */
    public VentanaCliente() {
        initComponents();
        this.setLocation(270, 165);
        //this.setAlwaysOnTop(true);
        mostrarTabla();
        seleccionarTabla();

    }

    public void mostrarTabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        rs = Conexion.getTabla("select *from cliente");
        //se asignan los nombre de la columna
        modelo.setColumnIdentifiers(new Object[]
        {
            "ID_Cliente", "Nombre", "Apellido paterno", "Apellido materno", "Teléfono","Correo electrónico"});

        try
        {
            while (rs.next())
            {
                modelo.addRow(new Object[]
                {
                    rs.getString("id_cliente"),
                    rs.getString("nombre"),
                    rs.getString("apellido_paterno"),
                    rs.getString("apellido_materno"),
                    rs.getString("telefono"),
                    rs.getString("correo_elec")
                });

            }
            tablaClientes.setModel(modelo);
        } catch (Exception e)
        {
            //JOptionPane.showMessageDialog(null, e);
        }
        //seleccionarTabla();
    }

    public void limpiar() {
        cId.setText("");
        cNombre.setText("");
        cApelliop.setText("");
        cApellidom.setText("");
        cCorreo.setText("");
        cTelefono.setText("");
        tablaClientes.setRowSelectionAllowed(false);
        botonRegistrar.setEnabled(true);
        mostrarTabla();

    }

    private void seleccionarTabla() {
        tablaClientes.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                limpiar();
                int row = tablaClientes.rowAtPoint(e.getPoint());
                cId.setText(tablaClientes.getValueAt(row, 0).toString());
                cNombre.setText(tablaClientes.getValueAt(row, 1).toString());
                cApelliop.setText(tablaClientes.getValueAt(row, 2).toString());
                cApellidom.setText(tablaClientes.getValueAt(row, 3).toString());
                cTelefono.setText(tablaClientes.getValueAt(row, 4).toString());
                cCorreo.setText(tablaClientes.getValueAt(row, 5).toString());
                botonRegistrar.setEnabled(false);

            }
        });

    }

    /*public void mostrarComboProv() {
        try
        {
            rs = Conexion.getTabla("select *from proveedor");
            while (rs.next())
            {
                comboBuscar.addItem(rs.getString("nombre"));
            }
        } catch (SQLException ex)
        {
            Logger.getLogger(VentanaInsumos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        bEliminar = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        bActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cApelliop = new javax.swing.JTextField();
        cId = new javax.swing.JTextField();
        cApellidom = new javax.swing.JTextField();
        bReparacion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cNombre = new javax.swing.JTextField();
        cTelefono = new javax.swing.JTextField();
        bLimpiar1 = new javax.swing.JButton();
        cCorreo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        botonSalir.setBackground(new java.awt.Color(51, 51, 51));
        botonSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setToolTipText("");

        tablaClientes.setBackground(new java.awt.Color(153, 153, 153));
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaClientes.setAutoscrolls(false);
        tablaClientes.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(tablaClientes);

        bEliminar.setBackground(new java.awt.Color(51, 51, 51));
        bEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bEliminar.setForeground(new java.awt.Color(255, 255, 255));
        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });

        botonRegistrar.setBackground(new java.awt.Color(51, 51, 51));
        botonRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        botonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        bActualizar.setBackground(new java.awt.Color(51, 51, 51));
        bActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bActualizar.setForeground(new java.awt.Color(255, 255, 255));
        bActualizar.setText("Actualizar");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/panaderoVentana.png"))); // NOI18N
        jLabel1.setText("Registro de Clientes");

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel3.setText("Id:");

        jLabel5.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel5.setText("Apellido paterno:");

        cApelliop.setEditable(true);
        cApelliop.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cApelliop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cApelliop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cApelliopActionPerformed(evt);
            }
        });

        cId.setEditable(true);
        cId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cId.setToolTipText("");
        cId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cApellidom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cApellidom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cApellidom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cApellidomActionPerformed(evt);
            }
        });

        bReparacion.setBackground(new java.awt.Color(51, 51, 51));
        bReparacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bReparacion.setForeground(new java.awt.Color(255, 255, 255));
        bReparacion.setText("Generar reparación");
        bReparacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReparacionActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel7.setText("Teléfono:");

        jLabel8.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel8.setText("Apellido materno:");

        jLabel9.setFont(new java.awt.Font("Sitka Banner", 1, 20)); // NOI18N
        jLabel9.setText("Correo electrónico:");

        cNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cTelefono.setEditable(true);
        cTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cTelefono.setToolTipText("");
        cTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTelefonoActionPerformed(evt);
            }
        });
        cTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cTelefonoKeyTyped(evt);
            }
        });

        bLimpiar1.setBackground(new java.awt.Color(51, 51, 51));
        bLimpiar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bLimpiar1.setForeground(new java.awt.Color(255, 255, 255));
        bLimpiar1.setText("Limpiar");
        bLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiar1ActionPerformed(evt);
            }
        });

        cCorreo.setEditable(true);
        cCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cCorreo.setToolTipText("");
        cCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(293, 293, 293)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cId, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cTelefono)
                                                    .addComponent(cApellidom)
                                                    .addComponent(cApelliop)
                                                    .addComponent(cNombre)
                                                    .addComponent(cCorreo, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(bActualizar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                                .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(62, 62, 62)
                                                .addComponent(bLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(36, 36, 36)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSalir)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cId, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cNombre))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cApelliop, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cApellidom, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1104, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        // TODO add your handling code here:

        int option = JOptionPane.showConfirmDialog(null, "¿Deseas continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION)
        {
            try
            {
                Connection conexion = Conexion.getConexion();
                ps = conexion.prepareStatement("delete from cliente where id_cliente=?");
                ps.setString(1, cId.getText());
                int resultado = ps.executeUpdate();
                if (resultado > 0)
                {
                    JOptionPane.showMessageDialog(null, "Eliminacion correcta");
                    mostrarTabla();
                } else
                {
                    JOptionPane.showMessageDialog(null, "No se realizo la eliminación de los datos");
                }
                conexion.close();
            } catch (Exception e)
            {
                System.err.println(e);
            }
            limpiar();
            tablaClientes.setRowSelectionAllowed(false);
            botonRegistrar.setEnabled(true);
        } else
        {
            System.out.println("El usuario seleccionó 'No'.");
        }
    }//GEN-LAST:event_bEliminarActionPerformed

    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        // TODO add your handling code here:

        int option = JOptionPane.showConfirmDialog(null, "¿Deseas continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION)
        {
            Connection conexion = null;
            int resultado = 0;
            boolean yaRegistrado;
            try
            {
                conexion = Conexion.getConexion();
                ps = conexion.prepareStatement("insert into cliente(id_cliente,nombre,apellido_paterno,apellido_materno,telefono, correo_elec)values(?,?,?,?,?,?)");
                ps.setString(1, cId.getText());
                ps.setString(2, cNombre.getText());
                ps.setString(3, cApelliop.getText());
                ps.setString(4, cApellidom.getText());
                ps.setString(5, cTelefono.getText());
                ps.setString(6, cCorreo.getText());

                if(cId.getText().equals("") ||cNombre.getText().equals("") || cApelliop.getText().equals("") ||cApellidom.getText().equals("") 
                        ||cTelefono.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Rellene todos los campos "); 
                }else if(cCorreo.getText().contains("@") && cCorreo.getText().contains(".")){    
                        resultado = ps.executeUpdate(); 
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Introduzca un correo válido "); }
                if ((resultado > 0))
                {
                    JOptionPane.showMessageDialog(null, "Datos ingresados correctamente");
                    limpiar();
                    mostrarTabla();
                } else
                {
                    JOptionPane.showMessageDialog(null, "Verifique que los datos sean correctos");

                }
                conexion.close();

            } catch (Exception ex)
            {
                JOptionPane.showMessageDialog(null, "Verifique los datos");
                System.out.println(ex);
            }
            tablaClientes.setRowSelectionAllowed(false);
            botonRegistrar.setEnabled(true);
        } else
        {

        }
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        // TODO add your handling code here:

        int option = JOptionPane.showConfirmDialog(null, "¿Deseas continuar?", "Confirmación", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION)
        {
            resultado = 0;
            try
            {
                Connection conexion = Conexion.getConexion();
                ps = conexion.prepareStatement("update cliente set nombre=?,apellido_paterno=?,apellido_materno=?,telefono=?, correo_elec=? where id_cliente=?");
                ps.setString(1, cNombre.getText());
                ps.setString(2, cApelliop.getText());
                ps.setString(3, cApellidom.getText());
                ps.setString(3, cTelefono.getText());
                ps.setString(4, cCorreo.getText());
                ps.setString(6, cId.getText());
                
                if(cNombre.getText().equals("") || cApelliop.getText().equals("") ||cApellidom.getText().equals("") 
                        ||cTelefono.getText().equals("") ||  cId.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Rellene todos los campos "); 
                }else if(cId.getText().contains("@") && cId.getText().contains(".")){    
                        resultado = ps.executeUpdate(); 
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Introduzca un correo válido "); }

                if ((resultado > 0))
                {
                    JOptionPane.showMessageDialog(null, "Datos actualizados correctamente");
                    limpiar();
                } else
                {
                    JOptionPane.showMessageDialog(null, "No fue posible actualizar los datos");
                }
                conexion.close();
            } catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "Verifique los datos");
            }
            mostrarTabla();
            limpiar();
            tablaClientes.setRowSelectionAllowed(false);
            botonRegistrar.setEnabled(true);
        } else
        {

        }
    }//GEN-LAST:event_bActualizarActionPerformed

    private void cApelliopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cApelliopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cApelliopActionPerformed

    private void bReparacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReparacionActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        vr.setVisible(true);
    }//GEN-LAST:event_bReparacionActionPerformed

    private void cApellidomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cApellidomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cApellidomActionPerformed

    private void bLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiar1ActionPerformed
         limpiar();
    }//GEN-LAST:event_bLimpiar1ActionPerformed

    private void cTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTelefonoKeyTyped
 int key = evt.getKeyChar();

    boolean numeros = key >= 48 && key <= 57;
        
    if (!numeros)
    {
        evt.consume();
    }

    if (cTelefono.getText().trim().length() == 10) {
        evt.consume();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_cTelefonoKeyTyped

    private void cTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTelefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bLimpiar1;
    private javax.swing.JButton bReparacion;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JTextField cApellidom;
    private javax.swing.JTextField cApelliop;
    private javax.swing.JTextField cCorreo;
    private javax.swing.JTextField cId;
    private javax.swing.JTextField cNombre;
    private javax.swing.JTextField cTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables

}
